### ISSUE TITLE
survey about dataset (and text generation model)

### ISSUE THREAD

**Issue by t0d4** [t0d4/informal-gpt#3]
インフォーマルな文を生成するように強化学習を通じて誘導する際に利用するコーパスもインフォーマル寄りな文体だと学習が早そう。そのようなデータセットを探す

- [x] インフォーマルな文体を比較的多く収録したコーパスの調査
- [x] （もしあれば）それらのデータセットでファインチューニングされたGPT系モデル

**Comment by t0d4** [comment]
今のところ見つけてくれたものは

- [GYAFC (Grammarly’s Yahoo Answers Formality Corpus)](https://paperswithcode.com/dataset/gyafc)
  - the largest dataset for any style containing a total of 110K informal / formal sentence pairs.
- [The National University of Singapore SMS Corpus](https://www.kaggle.com/datasets/rtatman/the-national-university-of-singapore-sms-corpus)
  - A corpus of more than 67,000 SMS messages in Singapore English & Mandarin

**Comment by wakataku8** [comment]
HuggingFaceのDatasetsにいくつか使えそうなのあった。daily dialogとかcasual conversation系

- [daily dialog]( https://huggingface.co/datasets/daily_dialog)
- [casual-conversation](https://huggingface.co/datasets/SohamGhadge/casual-conversation) 
- [reddit_casual_conversation_for_alpaca_lora](https://huggingface.co/datasets/binhgiangnguyendanh/reddit_casual_conversation_for_alpaca_lora)

**Comment by wakataku8** [comment]
あと、センテンスとそのフォーマリティスコアがセットになったものもあった。正負がフォーマル/インフォーマルを表していて、絶対値がその度合いかな。このデータセットでスコアが負のやつだけ取り出して使えばインフォーマルデータセットになる。
[pavlick-formality-scores](https://huggingface.co/datasets/osyvokon/pavlick-formality-scores)

**Comment by t0d4** [comment]
データセット結構あるんだな
こういうデータを使うとして、おそらくインフォーマルなデータ「のみ」を学習に使うとformality rankerが毎回informal寄りの高いスコアしか出さなくなるのでそれはそれで報酬モデルの勾配が消失して訓練がうまくいかなくなる気がするんだよね。
informal : formal = 4 : 1くらいで混ぜるとかがいいのかも

**Comment by wakataku8** [comment]
なるほど確かに。フォーマルなデータも混ざっているものとしてはKaggleのデータセットに
[3K Conversations Dataset for ChatBot](https://www.kaggle.com/datasets/kreeshrajani/3k-conversations-dataset-for-chatbot)
もあった。
The dataset may include various types of conversations such as casual or formal discussions, interviews, customer service interactions, or social media conversations.
と書いてあるけど、どのくらいの比率かは分からんな

**Comment by wakataku8** [comment]
Redditのコメントチェーンから抽出された147M件の会話で学習されたGPT系モデルを発見！
[DialoGPT](https://huggingface.co/docs/transformers/model_doc/dialogpt#dialogpt)
